config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/synopsis', as: 'synopsis'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def synopsis
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_cast_staff.html.erb
<div id="cast_staff" class="cast_staff main_content text-center">
  <h3>Cast</h3>

  <div class="row">
    <div class="cast1 col-md-3 col-md-offset-2 text-left">
      <div class="cast1-image"></div>

      <p>
        <strong>役1/役2</strong><br>
        大物ベストセラー作家。<br>
    	出版する本はすべてベストセラーになるほどの売れっ子作家だった彼だが…。
      </p>

      <p>
    	<strong>actor1</strong><br>
    	19XX年生まれ。代表作にドラマ「title1」(XX)、「title2」(XX)、
    	「title3」(XX)、映画「title4」(XX)、「title1」(XX)など。
      </p>
    </div>

    <div class="cast2 col-md-3 col-md-offset-2 text-left">
      <div class="cast2-image"></div>

      <p>
    	<strong>役1/役2</strong><br>
    	大物ベストセラー作家の大ファン。<br>
    	父の遺品である壊れた懐中時計が彼の体に触れた瞬間に…。
      </p>

      <p>
    	<strong>actor2</strong><br>
    	19XX年生まれ。代表作にドラマ「title1」(XX)、「title2」(XX)、「title3」(XX)、映画「title4」(XX)、「title1」(XX)など。
      </p>
    </div>
  </div>

  <div class="row">
	<div class="cast3 col-md-3 col-md-offset-2 text-left">
	  <div class="cast3-image"></div>

	  <p>
    	<strong>役1/役2</strong><br>
    	謎のゴーストライター。<br>
    	すべてがベールに包まれている謎の人物。
      </p>

      <p>
    	<strong>actor3</strong><br>
    	2XXX年生まれ。代表作にドラマ「title1」(XX)、「title2」(XX)、「title3」(XX)、映画「title4」(XX)、「title1」(XX)など。
      </p>
	</div>

	<div class="cast4 col-md-3 col-md-offset-2 text-left">
	  <div class="cast4-image"></div>

	  <p>
    	<strong>役1/役2</strong><br>
    	小説家。ベストセラー作家のライバルであり、文壇の2代アイドル。<br>
    	いつもベストセラー作家と比較されるため嫉妬と劣等感、
    	憤怒の感情に囚われている。
      </p>

      <p>
    	<strong>actor4</strong><br>
    	19XX年生まれ。代表作にドラマ「title1」(XX)、「title2」(XX)、「title3」(XX)、映画「title4」(XX)、「title1」(XX)など。
      </p>
	</div>
  </div>

  <h3>Staff</h3>
  <p>
	【演出】<span>演出家</span>「title1」 
	x 
	【脚本】<span>脚本家</span>「title2」
  </p>
</div>

app/views/homes/_gallery.html.erb
<div class="row">
  <div id="gallery" class="gallery main_content">
    <h3>Gallery</h3>

    <div class="gallery-images col-md-8 col-md-offset-2">
    	<div class="gallery-image1"></div>
    	<div class="gallery-image2"></div>
    	<div class="gallery-image3"></div>
    	<div class="gallery-image4"></div>
    	<div class="gallery-image5"></div>
    	<div class="gallery-image6"></div>
    </div>
  </div>
</div>

app/views/homes/_introduction.html.erb
<div id="introduction" class="introduction main_content text-center">
  <div class="row">
  	<h3>Introduction</h3>
    <h4>時を越えた運命の出会いー</h4>

    <div class="intro_actor1 col-md-2 col-md-offset-1"></div>
    <div class="intro_actor2 col-md-2 col-md-offset-1"></div>
    <div class="intro_actor3 col-md-2 col-md-offset-1"></div>
  </div>

  <div class="intro_actor text-center">
    <h5>
      [若手実力派No.1] <strong>actor1</strong> 
      x [国民的女優] <strong>actor2</strong> 
      x [次世代俳優] <strong>actor3</strong> 
      豪華共演！
    </h5>

    <p>
      「title1」「title2」など映画やドラマの数々で演技を褒められてきた若手実力派俳優actor1と、<br>
      「title3」以来6年ぶりのドラマ出演となる国民的女優actor2、<br>
      そして「title4」に出演し日本のファンを魅了した次世代注目俳優actor3が集結し豪華共演が実現！
    </p>

    <h5>
      過去と現在ー二つの時代をつなぐ運命的な物語を描く
    </h5>

    <p>
      スランプに陥ったベストセラー作家と謎のゴーストライター、そしてー<br>
      二つの時代を背景に、１通の手紙に絡んだ3人の物語。
    </p>

    <h5>
      「title5」脚本家 x「title6」監督 x 「title7」音響監督<br>
      最強タッグがドラマチックな物語を盛り上げる！
    </h5>

    <p>
      「title5」を手掛けた脚本家と「title6」のプロデューサーが<br>
      タッグを組み、さらには20XX年大ヒットドラマ「title7」でOST旋風を起こした<br>
      音響監督が本作OSTに携わり、アンティークで神秘的なドラマの雰囲気を盛り上げる。
    </p>
  </div>

  <div class="intro_image row">
    <div class="intro_image1 col-md-2 col-md-offset-1"></div>
    <div class="intro_image2 col-md-2 col-md-offset-1"></div>
    <div class="intro_image3 col-md-2 col-md-offset-1"></div>
    <div class="intro_image4 col-md-2 col-md-offset-1"></div>
  </div>
</div>

app/views/homes/_product_oa.html.erb
<div id="product_oa" class="product_oa main_content text-center">
  <h3>DVD<span>&</span>OA</h3>

  <div class="sell">
    <p class="product_oa_title">
	  Sell セル<br>
	  [全2BOX/全22話]
    </p>

    <div class="line text-center">
      <p>・-・-・-・-・-・-・</p>
    </div>

    <div class="sell_1 row">
      <div class="dvd col-md-1 col-md-offset-5">
	  	<div class="dvd_image"></div>
	  </div>

	  <div class="dvd_intro col-md-6 text-left">
	  	<p>
	  	  <strong>DVD-BOX1</strong>
	  	  20XX年<span>3</span>月<span>2</span>(金)発売<br>
	  	  ￥15,000+税<br>
	  	  6枚組 (第1話〜第11話収録)<br>
	  	  ●封入特典<br>
	  	  ・ストーリーブック<br>
	  	  ●特典映像<br>
	  	  ・特番<完全版><br>
	  	</p>
	  </div>
	</div>

	<div class="sell_2 row">
	  <div class="dvd col-md-1 col-md-offset-5">
	  	<div class="dvd_image"></div>
	  </div>

	  <div class="dvd_intro col-md-6 text-left">
	  	<p>
	  	  <strong>DVD-BOX2</strong>
	  	  20XX年<span>4</span>月<span>4</span>(金)発売<br>
	  	  ￥15,000+税<br>
	  	  6枚組 (第12話〜第22話収録)<br>
	  	  ●封入特典<br>
	  	  ・ストーリーブック<br>
	  	  ●特典映像<br>
	  	  ・メイキング<br>
	  	</p>
	  </div>
	</div>
  </div>

  <div class="rental">
	<p class="product_oa_title">
	  Rental レンタル<br>
	  [全12巻/全22話]
    </p>

    <div class="line text-center">
      <p>・-・-・-・-・-・-・</p>
    </div>

	<p>
	  vol.<span>1〜6</span>(第1話〜第11話収録) 
	  20XX年<span>3</span>月<span>2</span>(金)レンタル
	</p>

	<p>
	  vol.<span>7〜12</span>(第12話〜最終話収録) 
	  20XX年<span>4</span>月<span>4</span>(金)レンタル
	</p>
  </div>

  <div class="oa">
	<p class="product_oa_title">
	  OA オンエア<br>
	</p>

    <div class="line text-center">
      <p>・-・-・-・-・-・-・</p>
    </div>

	<p>
	  <span>XXTV</span>にて
	  20XX年<span>7</span>月<span>15</span>(土)より放送
	</p>

	<p>
	  <span>XXTV</span>にて
	  20XX年<span>1</span>月<span>15</span>(月)より放送
	</p>
  </div>

  <div class="vod">
	<p class="product_oa_title">
	  VOD INFORMATION<br>
    </p>

    <div class="line text-center">
      <p>・-・-・-・-・-・-・</p>
    </div>

    <p>
      <span>レンタル同日以降、順次配信中！</span>
    </p>

    <ul>
      <li>
	    <a href="#unext.url">＊U-NEXT</a>
	  </li>

	  <li>
	    <a href="#RakutenTV.url">＊RakutenTV</a>
	  </li>

	  <li>
	    <a href="#ShowTime.url">＊ShowTime</a>
	  </li>
    </ul>
  </div>
</div>

app/views/homes/_story.html.erb
<div id="story" class="story main_content text-center">
  <h3>Story</h3>

  <p>
  	世界的ベストセラー作家であり、老若男女に人気がある作家XXは、彼の大ファンをストーカーだと勘違いする。<br>
  	彼はサイン会のために訪れたタイで、ある手紙を受け取る。<br>
  	また、ゴーストライターだという謎の男が現れ…。
  </p>

  <div class="line text-center">
    <p>・-・-・-・-・-・-・</p>
  </div>

  <div class="story_more">
    <%= link_to synopsis_path, data: {'turbolinks' => false} do %>
      <div class="story_more_image">
        <p>more...</p>
      </div>
    <% end %>
  </div>
</div>

app/views/homes/_synopsis.html.erb
<div id="story_slide">
  <%= render 'layouts/back_btn' %>
	<div id="stories">
	  <div class="story1">
	    <div class="synopsis text-left">
	      <p>
	      	<strong>第1話</strong><br>
	      	世界的ベストセラー作家であり、老若男女に人気がある作家XX。
	      	彼はサイン会のために訪れたXXXXで、ある手紙を受け取る…。
	      </p>
	    </div>
	  </div>
	  <div class="story2">
	  	<div class="synopsis text-left">
	      <p>
	      	<strong>第2話</strong><br>
	      	世界的ベストセラー作家であり、老若男女に人気がある作家XX。
	      	彼はサイン会のために訪れたXXXXで、ある手紙を受け取る…。
	      </p>
	    </div>
	  </div>
	  <div class="story3">
	  	<div class="synopsis text-left">
	      <p>
	      	<strong>第3話</strong><br>
	      	世界的ベストセラー作家であり、老若男女に人気がある作家XX。
	      	彼はサイン会のために訪れたXXXXで、ある手紙を受け取る…。
	      </p>
	    </div>
	  </div>
	  <div class="story4">
	  	<div class="synopsis text-left">
	      <p>
	      	<strong>第4話</strong><br>
	      	世界的ベストセラー作家であり、老若男女に人気がある作家XX。
	      	彼はサイン会のために訪れたタイで、ある手紙を受け取る…。
	      </p>
	    </div>
	  </div>
	  <div class="story5">
	  	<div class="synopsis text-left">
	      <p>
	      	<strong>第5話</strong><br>
	      	世界的ベストセラー作家であり、老若男女に人気がある作家XX。
	      	彼はサイン会のために訪れたXXXXで、ある手紙を受け取る…。
	      </p>
	    </div>
	  </div>
	  <div class="story6">
	  	<div class="synopsis text-left">
	      <p>
	      	<strong>第6話</strong><br>
	      	世界的ベストセラー作家であり、老若男女に人気がある作家XX。
	      	彼はサイン会のために訪れたXXXXで、ある手紙を受け取る…。
	      </p>
	    </div>
	  </div>
</div>

app/views/homes/synopsis.html.erb
<div class="synopsis_box">
  <%= render 'homes/synopsis' %>
</div>

app/views/homes/top.html.erb
<div class="header_1">
  <%= render 'layouts/header' %>
</div>
<div class="header_2">
  <%= render 'layouts/hamburger_btn' %>
</div>


<div class="main_image">
  <p>一通の手紙から始まった奇跡</p>
</div>

<a class="twitter_icon" href="https://twitter.com"></a>

<div class="main_info text-center">
  <h1>
    ジョットマーイ
  </h1>

  <div class="info_dvd row">
    <div class="info_dvd_left col-md-6">
  	  <h6>20XX.<span>3.2</span>(金)</h6>
  	  <p>DVD-BOX1発売 ＆ vol.1 レンタル開始!</p>
    </div>

    <div class="info_dvd_right col-md-6">
      <h6>20XX.<span>4.4</span>(金)</h6>
  	  <p>DVD-BOX2発売 ＆ vol.2 レンタル開始!</p>
    </div>
  </div>

  <div class="info_actor row">
    <p>actor1 <span>x</span> actor2 <span>x</span> actor3</p>
  </div>
</div>

<div class="main_contents">
  <%= render 'introduction' %>
  <%= render 'story' %>
  <%= render 'cast_staff' %>
  <%= render 'product_oa' %>
  <%= render 'gallery' %>
</div>

app/views/layouts/_back_btn.html.erb
<div class="back_btn text-left">
  <%= link_to '<<Back', root_path, class: 'btn' %>
</div>

app/views/layouts/_hamburger_btn.html.erb
<header class="header">
  <div id="menu">
  	<%= render 'layouts/header_list' %>
  </div>

  <div id="hm_icon">
  	<a class="menu_trigger" href="/">
  	  <span></span>
  	  <span></span>
  	  <span></span>
  	</a>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="header_nav navbar-fixed-top">
  	<%= render 'layouts/header_list' %>
  </nav>
</header>

app/views/layouts/_header_list.html.erb
<ul class="nav_list text-center">
  <li class="nav_list_item">
  	<a href="/">
  	  Top
  	  <p>トップ</p>
  	</a>
  </li>

  <li class="nav_list_item">
  	<a href="#introduction">
  	  Introduction
  	  <p>イントロダクション</p>
  	</a>
  </li>

  <li class="nav_list_item">
  	<a href="#story">
  	  Story
  	  <p>ストーリー</p>
  	</a>
  </li>

  <li class="nav_list_item">
  	<a href="#cast_staff">
  	  Cast<span>&</span>Staff
  	  <p>キャスト&スタッフ</p>
  	</a>
  </li>

  <li class="nav_list_item title_nav">
  	<h2 class="">
   	 ジョットマーイ
   	</h2>
  </li>

  <li class="nav_list_item">
  	<a href="#product_oa">
  	  Product<span>&</span>OA
  	  <p>商品&放送</p>
  	</a>
  </li>

  <li class="nav_list_item">
  	<a href="#gallery">
  	  Gallery
  	  <p>ギャラリー</p>
  	</a>
  </li>

  <li class="nav_list_item">
  	<a href="https://www.youtube.com">
  	  Trailer
  	  <p>予告編</p>
    </a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ジョットマーイ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background_image">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>